/* File generated by the BNF Converter (bnfc 2.9.5). */

#ifndef SKELETON_HEADER
#define SKELETON_HEADER
/* You might want to change the above name. */

#include "Absyn.h"


void visitInput(Input p);
void visitJob(Job p);
void visitCommandLine(CommandLine p);
void visitOptRedir(OptRedir p);
void visitPipeline(Pipeline p);
void visitSimpleCommand(SimpleCommand p);
void visitListWord(ListWord p);

void visitWord(Word p);
void visitIdent(Ident i);
void visitInteger(Integer i);
void visitDouble(Double d);
void visitChar(Char c);
void visitString(String s);

#endif

