/* File generated by the BNF Converter (bnfc 2.9.5). */

/*** Visitor Traversal Skeleton. ***/
/* This traverses the abstract syntax tree.
   To use, copy Skeleton.h and Skeleton.c to
   new files. */

#include <stdlib.h>
#include <stdio.h>

#include "Skeleton.h"

void visitInput(Input p)
{
  switch(p->kind)
  {
  case is_StartInput:
    /* Code for StartInput Goes Here */
    visitJob(p->u.startinput_.job_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Input!\n");
    exit(1);
  }
}

void visitJob(Job p)
{
  switch(p->kind)
  {
  case is_Foreground:
    /* Code for Foreground Goes Here */
    visitCommandLine(p->u.foreground_.commandline_);
    break;
  case is_Background:
    /* Code for Background Goes Here */
    visitCommandLine(p->u.background_.commandline_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Job!\n");
    exit(1);
  }
}

void visitCommandLine(CommandLine p)
{
  switch(p->kind)
  {
  case is_MkCmdLine:
    /* Code for MkCmdLine Goes Here */
    visitPipeline(p->u.mkcmdline_.pipeline_);
    visitOptRedir(p->u.mkcmdline_.optredir_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing CommandLine!\n");
    exit(1);
  }
}

void visitOptRedir(OptRedir p)
{
  switch(p->kind)
  {
  case is_NoRedir:
    /* Code for NoRedir Goes Here */
    break;
  case is_InOutRedir:
    /* Code for InOutRedir Goes Here */
    visitWord(p->u.inoutredir_.word_1);
    visitWord(p->u.inoutredir_.word_2);
    break;
  case is_OutInRedir:
    /* Code for OutInRedir Goes Here */
    visitWord(p->u.outinredir_.word_1);
    visitWord(p->u.outinredir_.word_2);
    break;
  case is_OutAppendRedir:
    /* Code for OutAppendRedir Goes Here */
    visitWord(p->u.outappendredir_.word_);
    break;
  case is_ErrOutRedir:
    /* Code for ErrOutRedir Goes Here */
    visitWord(p->u.erroutredir_.word_);
    break;
  case is_ErrAppendRedir:
    /* Code for ErrAppendRedir Goes Here */
    visitWord(p->u.errappendredir_.word_);
    break;
  case is_OutRedir:
    /* Code for OutRedir Goes Here */
    visitWord(p->u.outredir_.word_);
    break;
  case is_InRedir:
    /* Code for InRedir Goes Here */
    visitWord(p->u.inredir_.word_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing OptRedir!\n");
    exit(1);
  }
}

void visitPipeline(Pipeline p)
{
  switch(p->kind)
  {
  case is_Single:
    /* Code for Single Goes Here */
    visitSimpleCommand(p->u.single_.simplecommand_);
    break;
  case is_Pipe:
    /* Code for Pipe Goes Here */
    visitSimpleCommand(p->u.pipe_.simplecommand_);
    visitPipeline(p->u.pipe_.pipeline_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Pipeline!\n");
    exit(1);
  }
}

void visitSimpleCommand(SimpleCommand p)
{
  switch(p->kind)
  {
  case is_MkSimpleCommand:
    /* Code for MkSimpleCommand Goes Here */
    visitWord(p->u.mksimplecommand_.word_);
    visitListWord(p->u.mksimplecommand_.listword_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing SimpleCommand!\n");
    exit(1);
  }
}

void visitListWord(ListWord p)
{
  switch(p->kind)
  {
  case is_NoMoreWord:
    /* Code for NoMoreWord Goes Here */
    break;
  case is_MoreWord:
    /* Code for MoreWord Goes Here */
    visitWord(p->u.moreword_.word_);
    visitListWord(p->u.moreword_.listword_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing ListWord!\n");
    exit(1);
  }
}

void visitWord(Word p)
{
  /* Code for Word Goes Here */
}
void visitIdent(Ident i)
{
  /* Code for Ident Goes Here */
}
void visitInteger(Integer i)
{
  /* Code for Integer Goes Here */
}
void visitDouble(Double d)
{
  /* Code for Double Goes Here */
}
void visitChar(Char c)
{
  /* Code for Char Goes Here */
}
void visitString(String s)
{
  /* Code for String Goes Here */
}

