/* File generated by the BNF Converter (bnfc 2.9.5). */

/*** Pretty Printer and Abstract Syntax Viewer ***/

#include <ctype.h>   /* isspace */
#include <stddef.h>  /* size_t */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "Printer.h"

#define INDENT_WIDTH 2

int _n_;
char *buf_;
size_t cur_;
size_t buf_size;

/* You may wish to change the renderC functions */
void renderC(Char c)
{
  if (c == '{')
  {
     onEmptyLine();
     bufAppendC(c);
     _n_ = _n_ + INDENT_WIDTH;
     bufAppendC('\n');
     indent();
  }
  else if (c == '(' || c == '[')
     bufAppendC(c);
  else if (c == ')' || c == ']')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC(' ');
  }
  else if (c == '}')
  {
     _n_ = _n_ - INDENT_WIDTH;
     onEmptyLine();
     bufAppendC(c);
     bufAppendC('\n');
     indent();
  }
  else if (c == ',')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC(' ');
  }
  else if (c == ';')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC('\n');
     indent();
  }
  else if (c == ' ') bufAppendC(c);
  else if (c == 0) return;
  else
  {
     bufAppendC(c);
     bufAppendC(' ');
  }
}

int allIsSpace(String s)
{
  char c;
  while ((c = *s++))
    if (! isspace(c)) return 0;
  return 1;
}

void renderS(String s)
{
  if (*s) /* s[0] != '\0', string s not empty */
  {
    if (allIsSpace(s)) {
      backup();
      bufAppendS(s);
    } else {
      bufAppendS(s);
      bufAppendC(' ');
    }
  }
}

void indent(void)
{
  int n = _n_;
  while (--n >= 0)
    bufAppendC(' ');
}

void backup(void)
{
  if (cur_ && buf_[cur_ - 1] == ' ')
    buf_[--cur_] = 0;
}

void removeTrailingSpaces()
{
  while (cur_ && buf_[cur_ - 1] == ' ') --cur_;
  buf_[cur_] = 0;
}

void removeTrailingWhitespace()
{
  while (cur_ && (buf_[cur_ - 1] == ' ' || buf_[cur_ - 1] == '\n')) --cur_;
  buf_[cur_] = 0;
}

void onEmptyLine()
{
  removeTrailingSpaces();
  if (cur_ && buf_[cur_ - 1 ] != '\n') bufAppendC('\n');
  indent();
}
char *printInput(Input p)
{
  _n_ = 0;
  bufReset();
  ppInput(p, 0);
  return buf_;
}
char *showInput(Input p)
{
  _n_ = 0;
  bufReset();
  shInput(p);
  return buf_;
}
void ppInput(Input p, int _i_)
{
  switch(p->kind)
  {
  case is_StartInput:
    if (_i_ > 0) renderC(_L_PAREN);
    ppJob(p->u.startinput_.job_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Input!\n");
    exit(1);
  }
}

void ppJob(Job p, int _i_)
{
  switch(p->kind)
  {
  case is_Foreground:
    if (_i_ > 0) renderC(_L_PAREN);
    ppCommandLine(p->u.foreground_.commandline_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Background:
    if (_i_ > 0) renderC(_L_PAREN);
    ppCommandLine(p->u.background_.commandline_, 0);
    renderC('&');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Job!\n");
    exit(1);
  }
}

void ppCommandLine(CommandLine p, int _i_)
{
  switch(p->kind)
  {
  case is_MkCmdLine:
    if (_i_ > 0) renderC(_L_PAREN);
    ppPipeline(p->u.mkcmdline_.pipeline_, 0);
    ppOptRedir(p->u.mkcmdline_.optredir_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing CommandLine!\n");
    exit(1);
  }
}

void ppOptRedir(OptRedir p, int _i_)
{
  switch(p->kind)
  {
  case is_NoRedir:
    if (_i_ > 0) renderC(_L_PAREN);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_InOutRedir:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('<');
    ppIdent(p->u.inoutredir_.word_1, 0);
    renderC('>');
    ppIdent(p->u.inoutredir_.word_2, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_OutInRedir:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('>');
    ppIdent(p->u.outinredir_.word_1, 0);
    renderC('<');
    ppIdent(p->u.outinredir_.word_2, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_OutAppendRedir:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS(">>");
    ppIdent(p->u.outappendredir_.word_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_ErrOutRedir:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("2>");
    ppIdent(p->u.erroutredir_.word_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_ErrAppendRedir:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("2>>");
    ppIdent(p->u.errappendredir_.word_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_OutRedir:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('>');
    ppIdent(p->u.outredir_.word_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_InRedir:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('<');
    ppIdent(p->u.inredir_.word_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing OptRedir!\n");
    exit(1);
  }
}

void ppPipeline(Pipeline p, int _i_)
{
  switch(p->kind)
  {
  case is_Single:
    if (_i_ > 0) renderC(_L_PAREN);
    ppSimpleCommand(p->u.single_.simplecommand_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Pipe:
    if (_i_ > 0) renderC(_L_PAREN);
    ppSimpleCommand(p->u.pipe_.simplecommand_, 0);
    renderC('|');
    ppPipeline(p->u.pipe_.pipeline_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Pipeline!\n");
    exit(1);
  }
}

void ppSimpleCommand(SimpleCommand p, int _i_)
{
  switch(p->kind)
  {
  case is_MkSimpleCommand:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.mksimplecommand_.word_, 0);
    ppListWord(p->u.mksimplecommand_.listword_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing SimpleCommand!\n");
    exit(1);
  }
}

void ppListWord(ListWord p, int _i_)
{
  switch(p->kind)
  {
  case is_NoMoreWord:
    if (_i_ > 0) renderC(_L_PAREN);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_MoreWord:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.moreword_.word_, 0);
    ppListWord(p->u.moreword_.listword_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing ListWord!\n");
    exit(1);
  }
}

void ppInteger(Integer n, int i)
{
  char tmp[20];
  sprintf(tmp, "%d", n);
  renderS(tmp);
}
void ppDouble(Double d, int i)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  renderS(tmp);
}
void ppChar(Char c, int i)
{
  bufAppendC('\'');
  bufEscapeC(c);
  bufAppendC('\'');
  bufAppendC(' ');
}
void ppString(String s, int i)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
  bufAppendC(' ');
}
void ppIdent(String s, int i)
{
  renderS(s);
}

void ppWord(String s, int i)
{
  renderS(s);
}


void shInput(Input p)
{
  switch(p->kind)
  {
  case is_StartInput:
    bufAppendC('(');

    bufAppendS("StartInput");

    bufAppendC(' ');

    shJob(p->u.startinput_.job_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Input!\n");
    exit(1);
  }
}

void shJob(Job p)
{
  switch(p->kind)
  {
  case is_Foreground:
    bufAppendC('(');

    bufAppendS("Foreground");

    bufAppendC(' ');

    shCommandLine(p->u.foreground_.commandline_);

    bufAppendC(')');

    break;
  case is_Background:
    bufAppendC('(');

    bufAppendS("Background");

    bufAppendC(' ');

    shCommandLine(p->u.background_.commandline_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Job!\n");
    exit(1);
  }
}

void shCommandLine(CommandLine p)
{
  switch(p->kind)
  {
  case is_MkCmdLine:
    bufAppendC('(');

    bufAppendS("MkCmdLine");

    bufAppendC(' ');

    shPipeline(p->u.mkcmdline_.pipeline_);
  bufAppendC(' ');
    shOptRedir(p->u.mkcmdline_.optredir_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing CommandLine!\n");
    exit(1);
  }
}

void shOptRedir(OptRedir p)
{
  switch(p->kind)
  {
  case is_NoRedir:

    bufAppendS("NoRedir");




    break;
  case is_InOutRedir:
    bufAppendC('(');

    bufAppendS("InOutRedir");

    bufAppendC(' ');

    shIdent(p->u.inoutredir_.word_1);
  bufAppendC(' ');
    shIdent(p->u.inoutredir_.word_2);

    bufAppendC(')');

    break;
  case is_OutInRedir:
    bufAppendC('(');

    bufAppendS("OutInRedir");

    bufAppendC(' ');

    shIdent(p->u.outinredir_.word_1);
  bufAppendC(' ');
    shIdent(p->u.outinredir_.word_2);

    bufAppendC(')');

    break;
  case is_OutAppendRedir:
    bufAppendC('(');

    bufAppendS("OutAppendRedir");

    bufAppendC(' ');

    shIdent(p->u.outappendredir_.word_);

    bufAppendC(')');

    break;
  case is_ErrOutRedir:
    bufAppendC('(');

    bufAppendS("ErrOutRedir");

    bufAppendC(' ');

    shIdent(p->u.erroutredir_.word_);

    bufAppendC(')');

    break;
  case is_ErrAppendRedir:
    bufAppendC('(');

    bufAppendS("ErrAppendRedir");

    bufAppendC(' ');

    shIdent(p->u.errappendredir_.word_);

    bufAppendC(')');

    break;
  case is_OutRedir:
    bufAppendC('(');

    bufAppendS("OutRedir");

    bufAppendC(' ');

    shIdent(p->u.outredir_.word_);

    bufAppendC(')');

    break;
  case is_InRedir:
    bufAppendC('(');

    bufAppendS("InRedir");

    bufAppendC(' ');

    shIdent(p->u.inredir_.word_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing OptRedir!\n");
    exit(1);
  }
}

void shPipeline(Pipeline p)
{
  switch(p->kind)
  {
  case is_Single:
    bufAppendC('(');

    bufAppendS("Single");

    bufAppendC(' ');

    shSimpleCommand(p->u.single_.simplecommand_);

    bufAppendC(')');

    break;
  case is_Pipe:
    bufAppendC('(');

    bufAppendS("Pipe");

    bufAppendC(' ');

    shSimpleCommand(p->u.pipe_.simplecommand_);
  bufAppendC(' ');
    shPipeline(p->u.pipe_.pipeline_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Pipeline!\n");
    exit(1);
  }
}

void shSimpleCommand(SimpleCommand p)
{
  switch(p->kind)
  {
  case is_MkSimpleCommand:
    bufAppendC('(');

    bufAppendS("MkSimpleCommand");

    bufAppendC(' ');

    shIdent(p->u.mksimplecommand_.word_);
  bufAppendC(' ');
    shListWord(p->u.mksimplecommand_.listword_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing SimpleCommand!\n");
    exit(1);
  }
}

void shListWord(ListWord p)
{
  switch(p->kind)
  {
  case is_NoMoreWord:

    bufAppendS("NoMoreWord");




    break;
  case is_MoreWord:
    bufAppendC('(');

    bufAppendS("MoreWord");

    bufAppendC(' ');

    shIdent(p->u.moreword_.word_);
  bufAppendC(' ');
    shListWord(p->u.moreword_.listword_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing ListWord!\n");
    exit(1);
  }
}

void shInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  bufAppendS(tmp);
}
void shDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  bufAppendS(tmp);
}
void shChar(Char c)
{
  bufAppendC('\'');
  bufEscapeC(c);
  bufAppendC('\'');
}
void shString(String s)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
}
void shIdent(String s)
{
  bufAppendC('\"');
  bufAppendS(s);
  bufAppendC('\"');
}

void shWord(String s)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
}


void bufEscapeS(const char *s)
{
  if (s) while (*s) bufEscapeC(*s++);
}
void bufEscapeC(const char c)
{
  switch(c)
  {
    case '\f': bufAppendS("\\f" ); break;
    case '\n': bufAppendS("\\n" ); break;
    case '\r': bufAppendS("\\r" ); break;
    case '\t': bufAppendS("\\t" ); break;
    case '\v': bufAppendS("\\v" ); break;
    case '\\': bufAppendS("\\\\"); break;
    case '\'': bufAppendS("\\'" ); break;
    case '\"': bufAppendS("\\\""); break;
    default: bufAppendC(c);
  }
}

void bufAppendS(const char *s)
{
  size_t len = strlen(s);
  size_t n;
  while (cur_ + len >= buf_size)
  {
    buf_size *= 2; /* Double the buffer size */
    resizeBuffer();
  }
  for(n = 0; n < len; n++)
  {
    buf_[cur_ + n] = s[n];
  }
  cur_ += len;
  buf_[cur_] = 0;
}
void bufAppendC(const char c)
{
  if (cur_ + 1 >= buf_size)
  {
    buf_size *= 2; /* Double the buffer size */
    resizeBuffer();
  }
  buf_[cur_] = c;
  cur_++;
  buf_[cur_] = 0;
}
void bufReset(void)
{
  cur_ = 0;
  buf_size = BUFFER_INITIAL;
  resizeBuffer();
  memset(buf_, 0, buf_size);
}
void resizeBuffer(void)
{
  char *temp = (char *) malloc(buf_size);
  if (!temp)
  {
    fprintf(stderr, "Error: Out of memory while attempting to grow buffer!\n");
    exit(1);
  }
  if (buf_)
  {
    strncpy(temp, buf_, buf_size); /* peteg: strlcpy is safer, but not POSIX/ISO C. */
    free(buf_);
  }
  buf_ = temp;
}
char *buf_;
size_t cur_, buf_size;

