/* File generated by the BNF Converter (bnfc 2.9.5). */

#ifndef ABSYN_HEADER
#define ABSYN_HEADER

/* strdup was not in the ISO C standard before 6/2019 (C2x), but in POSIX 1003.1.
 * See: https://en.cppreference.com/w/c/experimental/dynamic/strdup
 * Setting _POSIX_C_SOURCE to 200809L activates strdup in string.h.
 */
#define _POSIX_C_SOURCE 200809L

#include <stddef.h>  /* NULL */
#include <string.h>  /* strdup */

/* C++ Abstract Syntax Interface.*/

/********************   TypeDef Section    ********************/

typedef int Integer;
typedef char Char;
typedef double Double;
typedef char* String;
typedef char* Ident;
typedef char* Word;

/********************   Forward Declarations    ***********************/
struct Input_;
typedef struct Input_ *Input;

struct Job_;
typedef struct Job_ *Job;

struct CommandLine_;
typedef struct CommandLine_ *CommandLine;

struct OptRedir_;
typedef struct OptRedir_ *OptRedir;

struct Pipeline_;
typedef struct Pipeline_ *Pipeline;

struct SimpleCommand_;
typedef struct SimpleCommand_ *SimpleCommand;

struct ListWord_;
typedef struct ListWord_ *ListWord;

/********************   Abstract Syntax Classes    ********************/

struct Input_
{
  enum { is_StartInput } kind;
  union
  {
    struct { Job job_; } startinput_;
  } u;
};

Input make_StartInput(Job p0);

struct Job_
{
  enum { is_Foreground, is_Background } kind;
  union
  {
    struct { CommandLine commandline_; } foreground_;
    struct { CommandLine commandline_; } background_;
  } u;
};

Job make_Foreground(CommandLine p0);
Job make_Background(CommandLine p0);

struct CommandLine_
{
  enum { is_MkCmdLine } kind;
  union
  {
    struct { OptRedir optredir_; Pipeline pipeline_; } mkcmdline_;
  } u;
};

CommandLine make_MkCmdLine(Pipeline p0, OptRedir p1);

struct OptRedir_
{
  enum { is_NoRedir, is_InOutRedir, is_OutInRedir, is_OutAppendRedir, is_ErrOutRedir, is_ErrAppendRedir, is_OutRedir, is_InRedir } kind;
  union
  {
    struct { Word word_1, word_2; } inoutredir_;
    struct { Word word_1, word_2; } outinredir_;
    struct { Word word_; } outappendredir_;
    struct { Word word_; } erroutredir_;
    struct { Word word_; } errappendredir_;
    struct { Word word_; } outredir_;
    struct { Word word_; } inredir_;
  } u;
};

OptRedir make_NoRedir(void);
OptRedir make_InOutRedir(Word p0, Word p1);
OptRedir make_OutInRedir(Word p0, Word p1);
OptRedir make_OutAppendRedir(Word p0);
OptRedir make_ErrOutRedir(Word p0);
OptRedir make_ErrAppendRedir(Word p0);
OptRedir make_OutRedir(Word p0);
OptRedir make_InRedir(Word p0);

struct Pipeline_
{
  enum { is_Single, is_Pipe } kind;
  union
  {
    struct { SimpleCommand simplecommand_; } single_;
    struct { Pipeline pipeline_; SimpleCommand simplecommand_; } pipe_;
  } u;
};

Pipeline make_Single(SimpleCommand p0);
Pipeline make_Pipe(SimpleCommand p0, Pipeline p1);

struct SimpleCommand_
{
  enum { is_MkSimpleCommand } kind;
  union
  {
    struct { ListWord listword_; Word word_; } mksimplecommand_;
  } u;
};

SimpleCommand make_MkSimpleCommand(Word p0, ListWord p1);

struct ListWord_
{
  enum { is_NoMoreWord, is_MoreWord } kind;
  union
  {
    struct { ListWord listword_; Word word_; } moreword_;
  } u;
};

ListWord make_NoMoreWord(void);
ListWord make_MoreWord(Word p0, ListWord p1);

/***************************   Cloning   ******************************/

Input clone_Input(Input p);
Job clone_Job(Job p);
CommandLine clone_CommandLine(CommandLine p);
OptRedir clone_OptRedir(OptRedir p);
Pipeline clone_Pipeline(Pipeline p);
SimpleCommand clone_SimpleCommand(SimpleCommand p);
ListWord clone_ListWord(ListWord p);

/********************   Recursive Destructors    **********************/

/* These free an entire abstract syntax tree
 * including all subtrees and strings.
 *
 * Will not work properly if there is sharing in the tree,
 * i.e., when some pointers are aliased.  In this case
 * it will attempt to free the same memory twice.
 */

void free_Input(Input p);
void free_Job(Job p);
void free_CommandLine(CommandLine p);
void free_OptRedir(OptRedir p);
void free_Pipeline(Pipeline p);
void free_SimpleCommand(SimpleCommand p);
void free_ListWord(ListWord p);


#endif
