/* File generated by the BNF Converter (bnfc 2.9.5). */

/* C Abstract Syntax Implementation. */

#include <stdio.h>
#include <stdlib.h>
#include "Absyn.h"

/********************   StartInput    ********************/

Input make_StartInput(Job p1)
{
    Input tmp = (Input) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating StartInput!\n");
        exit(1);
    }
    tmp->kind = is_StartInput;
    tmp->u.startinput_.job_ = p1;
    return tmp;
}

/********************   Foreground    ********************/

Job make_Foreground(CommandLine p1)
{
    Job tmp = (Job) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Foreground!\n");
        exit(1);
    }
    tmp->kind = is_Foreground;
    tmp->u.foreground_.commandline_ = p1;
    return tmp;
}

/********************   Background    ********************/

Job make_Background(CommandLine p1)
{
    Job tmp = (Job) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Background!\n");
        exit(1);
    }
    tmp->kind = is_Background;
    tmp->u.background_.commandline_ = p1;
    return tmp;
}

/********************   MkCmdLine    ********************/

CommandLine make_MkCmdLine(Pipeline p1, OptRedir p2)
{
    CommandLine tmp = (CommandLine) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating MkCmdLine!\n");
        exit(1);
    }
    tmp->kind = is_MkCmdLine;
    tmp->u.mkcmdline_.pipeline_ = p1;
    tmp->u.mkcmdline_.optredir_ = p2;
    return tmp;
}

/********************   NoRedir    ********************/

OptRedir make_NoRedir()
{
    OptRedir tmp = (OptRedir) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating NoRedir!\n");
        exit(1);
    }
    tmp->kind = is_NoRedir;
    return tmp;
}

/********************   InOutRedir    ********************/

OptRedir make_InOutRedir(Word p1, Word p2)
{
    OptRedir tmp = (OptRedir) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating InOutRedir!\n");
        exit(1);
    }
    tmp->kind = is_InOutRedir;
    tmp->u.inoutredir_.word_1 = p1;
    tmp->u.inoutredir_.word_2 = p2;
    return tmp;
}

/********************   OutInRedir    ********************/

OptRedir make_OutInRedir(Word p1, Word p2)
{
    OptRedir tmp = (OptRedir) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating OutInRedir!\n");
        exit(1);
    }
    tmp->kind = is_OutInRedir;
    tmp->u.outinredir_.word_1 = p1;
    tmp->u.outinredir_.word_2 = p2;
    return tmp;
}

/********************   OutAppendRedir    ********************/

OptRedir make_OutAppendRedir(Word p1)
{
    OptRedir tmp = (OptRedir) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating OutAppendRedir!\n");
        exit(1);
    }
    tmp->kind = is_OutAppendRedir;
    tmp->u.outappendredir_.word_ = p1;
    return tmp;
}

/********************   ErrOutRedir    ********************/

OptRedir make_ErrOutRedir(Word p1)
{
    OptRedir tmp = (OptRedir) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ErrOutRedir!\n");
        exit(1);
    }
    tmp->kind = is_ErrOutRedir;
    tmp->u.erroutredir_.word_ = p1;
    return tmp;
}

/********************   ErrAppendRedir    ********************/

OptRedir make_ErrAppendRedir(Word p1)
{
    OptRedir tmp = (OptRedir) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ErrAppendRedir!\n");
        exit(1);
    }
    tmp->kind = is_ErrAppendRedir;
    tmp->u.errappendredir_.word_ = p1;
    return tmp;
}

/********************   OutRedir    ********************/

OptRedir make_OutRedir(Word p1)
{
    OptRedir tmp = (OptRedir) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating OutRedir!\n");
        exit(1);
    }
    tmp->kind = is_OutRedir;
    tmp->u.outredir_.word_ = p1;
    return tmp;
}

/********************   InRedir    ********************/

OptRedir make_InRedir(Word p1)
{
    OptRedir tmp = (OptRedir) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating InRedir!\n");
        exit(1);
    }
    tmp->kind = is_InRedir;
    tmp->u.inredir_.word_ = p1;
    return tmp;
}

/********************   Single    ********************/

Pipeline make_Single(SimpleCommand p1)
{
    Pipeline tmp = (Pipeline) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Single!\n");
        exit(1);
    }
    tmp->kind = is_Single;
    tmp->u.single_.simplecommand_ = p1;
    return tmp;
}

/********************   Pipe    ********************/

Pipeline make_Pipe(SimpleCommand p1, Pipeline p2)
{
    Pipeline tmp = (Pipeline) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Pipe!\n");
        exit(1);
    }
    tmp->kind = is_Pipe;
    tmp->u.pipe_.simplecommand_ = p1;
    tmp->u.pipe_.pipeline_ = p2;
    return tmp;
}

/********************   MkSimpleCommand    ********************/

SimpleCommand make_MkSimpleCommand(Word p1, ListWord p2)
{
    SimpleCommand tmp = (SimpleCommand) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating MkSimpleCommand!\n");
        exit(1);
    }
    tmp->kind = is_MkSimpleCommand;
    tmp->u.mksimplecommand_.word_ = p1;
    tmp->u.mksimplecommand_.listword_ = p2;
    return tmp;
}

/********************   NoMoreWord    ********************/

ListWord make_NoMoreWord()
{
    ListWord tmp = (ListWord) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating NoMoreWord!\n");
        exit(1);
    }
    tmp->kind = is_NoMoreWord;
    return tmp;
}

/********************   MoreWord    ********************/

ListWord make_MoreWord(Word p1, ListWord p2)
{
    ListWord tmp = (ListWord) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating MoreWord!\n");
        exit(1);
    }
    tmp->kind = is_MoreWord;
    tmp->u.moreword_.word_ = p1;
    tmp->u.moreword_.listword_ = p2;
    return tmp;
}

/***************************   Cloning   ******************************/

Input clone_Input(Input p)
{
  switch(p->kind)
  {
  case is_StartInput:
    return make_StartInput (clone_Job(p->u.startinput_.job_));

  default:
    fprintf(stderr, "Error: bad kind field when cloning Input!\n");
    exit(1);
  }
}

Job clone_Job(Job p)
{
  switch(p->kind)
  {
  case is_Foreground:
    return make_Foreground (clone_CommandLine(p->u.foreground_.commandline_));

  case is_Background:
    return make_Background (clone_CommandLine(p->u.background_.commandline_));

  default:
    fprintf(stderr, "Error: bad kind field when cloning Job!\n");
    exit(1);
  }
}

CommandLine clone_CommandLine(CommandLine p)
{
  switch(p->kind)
  {
  case is_MkCmdLine:
    return make_MkCmdLine
      ( clone_Pipeline(p->u.mkcmdline_.pipeline_)
      , clone_OptRedir(p->u.mkcmdline_.optredir_)
      );

  default:
    fprintf(stderr, "Error: bad kind field when cloning CommandLine!\n");
    exit(1);
  }
}

OptRedir clone_OptRedir(OptRedir p)
{
  switch(p->kind)
  {
  case is_NoRedir:
    return make_NoRedir ();

  case is_InOutRedir:
    return make_InOutRedir
      ( strdup(p->u.inoutredir_.word_1)
      , strdup(p->u.inoutredir_.word_2)
      );

  case is_OutInRedir:
    return make_OutInRedir
      ( strdup(p->u.outinredir_.word_1)
      , strdup(p->u.outinredir_.word_2)
      );

  case is_OutAppendRedir:
    return make_OutAppendRedir (strdup(p->u.outappendredir_.word_));

  case is_ErrOutRedir:
    return make_ErrOutRedir (strdup(p->u.erroutredir_.word_));

  case is_ErrAppendRedir:
    return make_ErrAppendRedir (strdup(p->u.errappendredir_.word_));

  case is_OutRedir:
    return make_OutRedir (strdup(p->u.outredir_.word_));

  case is_InRedir:
    return make_InRedir (strdup(p->u.inredir_.word_));

  default:
    fprintf(stderr, "Error: bad kind field when cloning OptRedir!\n");
    exit(1);
  }
}

Pipeline clone_Pipeline(Pipeline p)
{
  switch(p->kind)
  {
  case is_Single:
    return make_Single (clone_SimpleCommand(p->u.single_.simplecommand_));

  case is_Pipe:
    return make_Pipe
      ( clone_SimpleCommand(p->u.pipe_.simplecommand_)
      , clone_Pipeline(p->u.pipe_.pipeline_)
      );

  default:
    fprintf(stderr, "Error: bad kind field when cloning Pipeline!\n");
    exit(1);
  }
}

SimpleCommand clone_SimpleCommand(SimpleCommand p)
{
  switch(p->kind)
  {
  case is_MkSimpleCommand:
    return make_MkSimpleCommand
      ( strdup(p->u.mksimplecommand_.word_)
      , clone_ListWord(p->u.mksimplecommand_.listword_)
      );

  default:
    fprintf(stderr, "Error: bad kind field when cloning SimpleCommand!\n");
    exit(1);
  }
}

ListWord clone_ListWord(ListWord p)
{
  switch(p->kind)
  {
  case is_NoMoreWord:
    return make_NoMoreWord ();

  case is_MoreWord:
    return make_MoreWord
      ( strdup(p->u.moreword_.word_)
      , clone_ListWord(p->u.moreword_.listword_)
      );

  default:
    fprintf(stderr, "Error: bad kind field when cloning ListWord!\n");
    exit(1);
  }
}

/********************   Recursive Destructors    **********************/

/* These free an entire abstract syntax tree
 * including all subtrees and strings.
 *
 * Will not work properly if there is sharing in the tree,
 * i.e., when some pointers are aliased.  In this case
 * it will attempt to free the same memory twice.
 */

void free_Input(Input p)
{
  switch(p->kind)
  {
  case is_StartInput:
    free_Job(p->u.startinput_.job_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when freeing Input!\n");
    exit(1);
  }
  free(p);
}

void free_Job(Job p)
{
  switch(p->kind)
  {
  case is_Foreground:
    free_CommandLine(p->u.foreground_.commandline_);
    break;

  case is_Background:
    free_CommandLine(p->u.background_.commandline_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when freeing Job!\n");
    exit(1);
  }
  free(p);
}

void free_CommandLine(CommandLine p)
{
  switch(p->kind)
  {
  case is_MkCmdLine:
    free_Pipeline(p->u.mkcmdline_.pipeline_);
    free_OptRedir(p->u.mkcmdline_.optredir_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when freeing CommandLine!\n");
    exit(1);
  }
  free(p);
}

void free_OptRedir(OptRedir p)
{
  switch(p->kind)
  {
  case is_NoRedir:
    break;

  case is_InOutRedir:
    free(p->u.inoutredir_.word_1);
    free(p->u.inoutredir_.word_2);
    break;

  case is_OutInRedir:
    free(p->u.outinredir_.word_1);
    free(p->u.outinredir_.word_2);
    break;

  case is_OutAppendRedir:
    free(p->u.outappendredir_.word_);
    break;

  case is_ErrOutRedir:
    free(p->u.erroutredir_.word_);
    break;

  case is_ErrAppendRedir:
    free(p->u.errappendredir_.word_);
    break;

  case is_OutRedir:
    free(p->u.outredir_.word_);
    break;

  case is_InRedir:
    free(p->u.inredir_.word_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when freeing OptRedir!\n");
    exit(1);
  }
  free(p);
}

void free_Pipeline(Pipeline p)
{
  switch(p->kind)
  {
  case is_Single:
    free_SimpleCommand(p->u.single_.simplecommand_);
    break;

  case is_Pipe:
    free_SimpleCommand(p->u.pipe_.simplecommand_);
    free_Pipeline(p->u.pipe_.pipeline_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when freeing Pipeline!\n");
    exit(1);
  }
  free(p);
}

void free_SimpleCommand(SimpleCommand p)
{
  switch(p->kind)
  {
  case is_MkSimpleCommand:
    free(p->u.mksimplecommand_.word_);
    free_ListWord(p->u.mksimplecommand_.listword_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when freeing SimpleCommand!\n");
    exit(1);
  }
  free(p);
}

void free_ListWord(ListWord p)
{
  switch(p->kind)
  {
  case is_NoMoreWord:
    break;

  case is_MoreWord:
    free(p->u.moreword_.word_);
    free_ListWord(p->u.moreword_.listword_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when freeing ListWord!\n");
    exit(1);
  }
  free(p);
}

